Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('post_detail/<slug:slug>', views.post_detail, name='post_detail')
]

Exporter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('ExporterLogin/', views.ExporterLogin, name='ExporterLogin'),
    path('ExporterSignup/', views.ExporterSignup, name='ExporterSignup'),
    path('Exporterlogout/', views.Exporterlogout, name='Exporterlogout'),
    path('dashboard/export_request/', views.export_request, name='export_request'),
    path('dashboard/get_types/', views.get_types, name='get_types'),
    path('dashboard/import_supply/', views.import_supply, name='import_supply'),
    path('dashboard/request_status/', views.request_status, name='request_status'),
    path('dashboard/orders/', views.orders, name='orders'),
    path('dashboard/stocks/', views.stocks, name='stocks'),
    path('dashboard/payments/', views.payments, name='payments'),
    path('dashboard/payments/send_payment_link/<order_number>/', views.send_payment_link, name='send_payment_link'),
    path('dashboard/payments/invoice/<order_number>/', views.invoice, name='invoice'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/profile/change_password/', views.change_password, name='change_password'),
    path('dashboard/profile/delete_account/', views.delete_account, name='delete_account'),
]

NECBDC/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('Blog.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    path('accounts/', include('Accounts.urls')),
    path('news/', include('News.urls')),
    path('projects/', include('Projects.urls')),
    path('exporter/', include('Exporter.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exporter/models.py
from django.db import models
from Accounts.models import Account
from django.db.models.signals import post_save
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from .constants import PaymentStatus, DeliveryStatus, RequestStatus, generate_request_number, generate_order_number
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from datetime import timedelta
import requests
import json



class Type(models.Model):
    type_name = models.CharField(max_length=100, unique=True ,default=False, choices=[
        ('Bambusa guvi', 'Bambusa guvi'),
        ('Bambusa bambua', 'Bambusa bambua'),
        ('Bambusa burmanica', 'Bambusa burmanica'),
        ('Bambusa vulgaris', 'Bambusa vulgaris'),
        ('Bambusa tulda', 'Bambusa tulda'),
    ])

    def __str__(self):
        return self.type_name

    def get_all_types():
        return Type.objects.all()

    def get_type_by_name(type_name):
        try:
            return Type.objects.get(type_name=type_name)
        except Type.DoesNotExist:
            return None


class Warehouse(models.Model):
    w_name = models.CharField(max_length=50)
    address = models.TextField(unique=True, blank=False, null=False)
    city = models.CharField(max_length=20, blank=False)
    state = models.CharField(max_length=20, blank=False)
    country = models.CharField(max_length=20, blank=False)
    

    def __str__(self):
        return self.country

    def get_all_warehouses():
        return Warehouse.objects.all()

    def get_warehouse_by_id(id):
        try:
            return Warehouse.objects.get(id=id)
        except Warehouse.DoesNotExist:
            return None


    def get_warehouse_by_name(w_name):
        try:
            return Warehouse.objects.get(w_name=w_name)
        except Warehouse.DoesNotExist:
            return None

    def get_warehouse_by_address(address):
        try:
            return Warehouse.objects.get(address=address)
        except Warehouse.DoesNotExist:
            return None




class WarehouseType(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    price_per_unit = models.IntegerField(blank=False, default=50)
    stock_capacity = models.IntegerField(blank=False, default=500)

    def __str__(self):
        return self.warehouse.w_name + ' ' + self.type.type_name

    def get_all_warehouse_types():
        return WarehouseType.objects.all()

    def get_warehouse_type_by_warehouse(warehouse):
        return WarehouseType.objects.filter(warehouse=warehouse)

    def get_warehouse_type_by_type(type):
        return WarehouseType.objects.filter(type=type)


class Request(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, default=False)
    request_number = models.CharField(max_length=30, default=generate_request_number, unique=True)
    type_name = models.CharField(max_length=100, default=False)
    warehouse = models.CharField(max_length=100, default=False)
    quantity = models.PositiveIntegerField()
    request_type = models.CharField(max_length=20, choices=[
        ('Export', 'Export'),
        ('Import', 'Import')
    ])
    pickup_date = models.DateField(blank=False, null=True)
    pickup_status = models.CharField(max_length=20, null=True, default=PaymentStatus.PENDING)
    is_verfied = models.CharField(max_length=20, default=RequestStatus.PENDING)

    delivery_status = models.CharField(max_length=20,null=True, default=DeliveryStatus.PENDING)
    cname = models.CharField(max_length=50, blank=False, default=False)
    cemail = models.EmailField(max_length=50, blank=False, default=False)
    cphone = models.CharField(max_length=50, blank=False, default=False)
    caddress = models.TextField(blank=False, default=False)
    city = models.CharField(max_length=20, blank=False, default=False)
    state = models.CharField(max_length=20, blank=False, default=False)
    country = models.CharField(max_length=20, blank=False, default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.request_number





class Order(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, default=False)
    contact_id = models.CharField(max_length=50, blank=True, null=True)
    request = models.OneToOneField(Request, on_delete=models.CASCADE, related_name='order')
    order_number = models.CharField(max_length=30, default=generate_order_number, unique=True)
    type_name = models.CharField(max_length=100, default=False)
    warehouse = models.CharField(max_length=100, default=False)
    quantity = models.PositiveIntegerField()
    order_type = models.CharField(max_length=20, choices=[
        ('Export', 'Export'),
        ('Import', 'Import')
    ])
    pickup_date = models.DateField(blank=False, null=True)
    pickup_status = models.CharField(max_length=20, null=True, default='PENDING')
    delivery_status = models.CharField(max_length=20,null=True, default=DeliveryStatus.PENDING)
    contact_id = models.CharField(max_length=50, blank=True, default=None, null=True)
    order_total = models.PositiveIntegerField(blank=True, default=500)
    cname = models.CharField(max_length=50, blank=False, default=False)
    cemail = models.EmailField(max_length=50, blank=False, default=False)
    cphone = models.CharField(max_length=50, blank=False, default=False)
    caddress = models.TextField(blank=False, default=False)
    city = models.CharField(max_length=20, blank=False, default=False)
    state = models.CharField(max_length=20, blank=False, default=False)
    country = models.CharField(max_length=20, blank=False, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_status = models.CharField(max_length=20, null=True, default=PaymentStatus.PENDING)
    reserved_until = models.DateTimeField(default=timezone.now)



    def __str__(self):
        return self.order_number


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, default=False)
    order = models.OneToOneField(Order, on_delete=models.CASCADE, blank=True, null=True)
    payment_id = models.CharField(max_length=100, blank=True)
    payment_link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=20, default=PaymentStatus.PENDING)
    amount = models.FloatField(null=True, blank=True)
    currency = models.CharField(max_length=10, default='INR', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order.order_number




@receiver(post_save, sender=Request)
def create_order_for_verified_request(sender, instance, created, **kwargs):
    if not created and instance.is_verfied == 'success':

        try:
            warehouse_type = WarehouseType.objects.get(
                warehouse=Warehouse.objects.get(w_name=instance.warehouse),
                type=Type.objects.get(type_name=instance.type_name)
            )
        except WarehouseType.DoesNotExist:       
            warehouse_type = WarehouseType.objects.create(warehouse=Warehouse.objects.get(w_name=instance.warehouse),
            type=Type.objects.get(type_name=instance.type_name), stock_capacity=500, price_per_unit=50)
            warehouse_type.save()

        print(warehouse_type, '################')
        tax = 0.18  # 18% tax
        quantity = instance.quantity
        price_per_unit = warehouse_type.price_per_unit
        order_total = (quantity * price_per_unit) + tax

        if instance.request_type == 'Import':
            warehouse_type.stock_capacity -= instance.quantity
            warehouse_type.save()
            order = Order.objects.create(
            request=instance,
            user = instance.user,
            type_name=instance.type_name,
            warehouse=instance.warehouse,
            quantity=instance.quantity,
            order_type=instance.request_type,
            order_total=order_total,
            pickup_date=instance.pickup_date,
            pickup_status=instance.pickup_status,
            delivery_status=instance.delivery_status,
            cname=instance.cname,
            cemail=instance.cemail,
            cphone=instance.cphone,
            caddress=instance.caddress,
            city=instance.city,
            state=instance.state,
            country=instance.country,
            reserved_until=timezone.now() + timedelta(hours=24)
            )
            payment = Payment.objects.create(
                user = instance.user,   
                order= order,
                status = PaymentStatus.PENDING,
                amount=order_total,
                currency='INR',
            )
            payment.save()
        elif instance.request_type == 'Export':
            warehouse_type.stock_capacity += instance.quantity
            warehouse_type.save()

            
            order = Order.objects.create(
                request=instance,
                user = instance.user,
                type_name=instance.type_name,
                warehouse=instance.warehouse,
                quantity=instance.quantity,
                order_type=instance.request_type,
                order_total=order_total,
                pickup_date=instance.pickup_date,
                pickup_status=instance.pickup_status,
                delivery_status=instance.delivery_status,
                cname=instance.cname,
                cemail=instance.cemail,
                cphone=instance.cphone,
                caddress=instance.caddress,
                city=instance.city,
                state=instance.state,
                country=instance.country,
                reserved_until=timezone.now() + timedelta(hours=24),
            )

            print(order.cname)
            
            url = "https://api.razorpay.com/v1/contacts"
            data = {

templates/Exporter/Dashboard/export_request.html
{% extends 'Exporter/Dashboard/base.html' %}
{% block content %}



<div id="app-content">
    <div class="app-content-area">
      <!-- Container fluid -->
      <div class="container-fluid">
        <div class="row">
          <div class=" col-xl-9 col-md-12 col-sm-12 col-12 ">
            <!-- Content -->
                
            
            <div class="page-header">
                    <h1>Export</h1>
                </div>

                <form action="{% url 'export_request' %}" method="POST">
                    {% csrf_token %}
                    {% include 'includes/alerts.html' %}

                <div class="mb-6">
                    <div class="card">
                    <!-- Tab content -->
                    <div class="tab-content p-4" id="pills-tabContent-basic-forms">
                        <div class="tab-pane tab-example-design fade show active" id="pills-basic-forms-design"
                        role="tabpanel" aria-labelledby="pills-basic-forms-design-tab">
                        
                        <div class="row">
                            <!-- Input -->
                            <div class="col-lg-6 mb-3">
                                <label class="form-label" for="warehouses">To WareHouse</label>
                                <select  id="warehouses" name="warehouse" class="form-select" aria-label="Default select example">
                                    <option selected>Open this select menu</option>
                                    {% for warehouse in warehouses %}
                                        <option value="{{ warehouse.w_name }}">{{ warehouse.country }}</option> 
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="col-lg-6 mb-3">
                                <label class="form-label" for="types">Type</label>
                                <select id="types" name="type_name" class="form-select" aria-label="Default select example"> 
                                    <option selected>Open this select menu</option>
                                    {% for type in types %}
                                        <option value="{{ type.type_name }}">{{type}}</option> 
                                    {% endfor %}
                                </select>
                            </div>
                            
                                <div class="col-lg-6 mb-3">
                                    <label class="form-label" for="textInput">Quantity</label>
                                    <input type="number" name="quantity" id="textInput" class="form-control" placeholder="Input Text">
                                </div>

                                <div class="col-lg-6 mb-3">
                                    <label class="form-label" for="textInput">Photos</label>
                                    <input type="file" name="photo" id="textInput" class="form-control" placeholder="Input Text">
                                </div>
                                
                                <div class="col-md-3 mb-3">
                                    <label for="validationCustom04" class="form-label">Customer Name</label>
                                    <input type="text" name="cname" class="form-control" id="validationCustom03" required>
                                </div>

                                <div class="col-md-3 mb-3">
                                    <label for="validationCustom04" class="form-label">Email Address</label>
                                    <input type="email" name="cemail" class="form-control" id="validationCustom03" required>
                                </div>

                                <div class="col-md-3 mb-3">
                                    <label for="validationCustom04" class="form-label">Phone No</label>
                                    <input type="phone" name="cphone" class="form-control" id="validationCustom03" required>
                                </div>
                            </div>


                            <div class="row">   
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom03" class="form-label">Address</label>
                                        <input type="text" name="caddress" class="form-control" id="validationCustom03" required>
                                        <div class="invalid-feedback">
                                            Please provide a valid city.
                                        </div>
                                    </div>
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom03" class="form-label">City</label>
                                        <input type="text" name="city" class="form-control" id="validationCustom03" required>
                                        <div class="invalid-feedback">
                                        Please provide a valid city.
                                        </div>
                                    </div>
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom04" class="form-label">State</label>
                                        <input type="text" name="state" class="form-control" id="validationCustom03" required>
                                    </div>
                                    
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom04"  class="form-label">Country</label>
                                        <input type="text" name="country" class="form-control" id="validationCustom03" required>
                                    </div>

                                    <div class="col-md-3 mb-3">
                                        <label for="validationCustom04" class="form-label">Pick Up Date</label>
                                        <input type="date" name="pickup_date" class="form-control" id="validationCustom03" required>
                                    </div>

                                    <div class="col-12 mb-3">
                                        <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                        <label class="form-check-label" for="invalidCheck">
                                            Agree to terms and conditions
                                        </label>
                                        <div class="invalid-feedback">
                                            You must agree before submitting.
                                        </div>
                                        </div>
                                    </div>
                                    <div class="col-12 mb-3">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </div>
                            </div>                        
                        </div>
                    </form>
                <div class="tab-pane tab-example-html fade " id="pills-basic-forms-html" role="tabpanel"
                aria-labelledby="pills-basic-forms-html-tab">

                                <pre><code class="language-markup"><span class="token comment">&lt;!-- Input --&gt;</span>
                        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>mb-3<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>
                        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form-label<span class="token punctuation">"</span></span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>textInput<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Input<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span>
                        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>textInput<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form-control<span class="token punctuation">"</span></span> <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>Input Text<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>
                        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">&gt;</span></span></code></pre>
                </div>
            </div>
        </div>
    </div>
</div>
{% comment %} <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>

    $(document).ready(function() {
        $('#warehouses').on('change', function() {
          var warehouseId = $(this).val();
          $.ajax({
            url: window.location.protocol + '//' + window.location.host + '/exporter/dashboard/get_types/',
            type: 'GET',
            data: { 'warehouse_id': warehouseId },
            success: function(data) {
              $('#types').empty();
              for (var i = 0; i < data.length; i++) {
                console.log(data[i].type_name);
                $('#types').append($('<option>', {
                  value: data[i].id,
                  text: data[i].type_name
                }));
              }
            }
          });
        });
      });
      
</script> {% endcomment %}

{% endblock content %}

templates/Exporter/Dashboard/invoice.html
{% extends 'Exporter/Dashboard/base.html' %}
{% block content %}
{% load static %}


<!-- Page Content -->
 <div id="app-content">

  <!-- Container fluid -->
  <div class="app-content-area">
    <div class="container-fluid">
      <div class="row">
        <div class="offset-xxl-2 col-xxl-8 col-md-12 col-12">
          <div class="card" id="invoice">
<!-- Page header -->
<div class="card-body">
<div class="row justify-content-between mb-md-10">
<div class="col-lg-3 col-md-6 col-12">
<a href="#" >
<img src="../assets/images/brand/logo/logo-2.svg" alt="" class="text-inverse">
</a>
<div class="mt-6">
{% if order.order_type == 'Import' %}
<span class="fw-semi-bold">Import From</span>
<p class="mt-2 mb-0">{{wh.address}}
</p>
<br><br>
<span class="fw-semi-bold">Delivery Address</span>
<p class="mt-2 mb-0">{{order.caddress}}
</p>
{% endif %}

</div>
</div>
<div class="col-lg-3 col-md-6 col-12 d-flex justify-content-md-end mt-4 mt-md-0">
  <ul class="list-unstyled">
      <li class="mb-1">
          <span>Invoice No. :</span>
          <span class="ms-2 text-dark">{{order.order_number}}</span>

      </li>
       <li class="mb-1">
          <span>Invoice date :</span>
          <span class="ms-2 text-dark">{{order.created_at}}</span>

      </li>
       <li class="mb-1">
          <span>Due Date :</span>
          <span class="ms-2 text-dark">{{order.reserved_until}}</span>
      </li>
      <li class="mb-1">
        <span>Order Type :</span>
        <span class="ms-2 text-dark">{{order.order_type}}</span>
    </li>
  </ul>


      </div>
</div>
<div class="row justify-content-between mb-8">
<div class="col-lg-3 col-md-6 col-12">

<div class="mt-6">
<span class="fw-semi-bold">Invoice To</span>
<h4>{{order.cname}}</h4>
<p class="mt-2 mb-2">{{order.caddress}}
</p>
<span>{{order.cemail}}</span><br>
<span class="fw-semi-bold">roberthernandez@gmail.com</span>
</div>
</div>
<div class="col-lg-3 col-md-6 col-12 d-flex justify-content-md-end mt-4 mt-md-0">
  <div class="mt-6">
      <span class="fw-semi-bold">Invoice From</span>
      <h4>Admin</h4>
      <p class="mt-2 mb-2">4333 Edwards Rdundefined <br> Erie, Oklahoma <br>14355 United States
      </p>
      <span>+1 (123) 456 7891</span><br>
      <span class="fw-semi-bold">dashui@example.com</span>
  </div>


      </div>
</div>
<div class="row">
<div class="col-12">
  <div class="table-responsive ">
      <table class="table table-centered text-nowrap">
          <thead class="table-light ">
            <tr>

              <th scope="col">Product Description</th>
              <th scope="col">Quantity</th>
              <th scope="col">Unit Price</th>
              <th scope="col">Amount (USD)</th>
            </tr>
          </thead>
          <tbody>
            <tr>

              <td><h5 class="mb-0">{{order.type_name}}</h5>
              <p class="mb-0">Lorem ipsum dolor sit amet, consectetur.</p>
              </td>
              <td>{{order.quantity}}</td>
              <td>{{order.price_per_unit}}</td>
              <td>$39.00</td>
            </tr>

            <tr>
              <td colspan="2" class="border-bottom-0">

              </td>
              <td><span class="text-dark">Sub Total</span></td>
              <td><span class="text-dark">$117.00</span></td>
            </tr>
            <tr>
              <td colspan="2" class="border-bottom-0">

              </td>
              <td><span class="text-dark">Net Amount</span></td>
              <td><span class="text-dark">$117.00</span></td>
            </tr>
            <tr>
              <td colspan="2" class="border-bottom-0">

              </td>
              <td><span class="text-dark">Tax*</span></td>
              <td><span class="text-dark">$2.00</span></td>
            </tr>
            <tr>
              <td colspan="2" class="border-bottom-0">

              </td>
              <td><span class="text-dark fw-bold">Total Amount</span></td>
              <td><span class="text-dark fw-bold">Rs.{{order.order_total}}</span></td>
            </tr>

            <img src="{% static 'images/paid.png' %}" alt="" srcset="">
          </tbody>
        </table>
  </div>

  <div class="border-top pt-8">
      <div >
          <h5 class="mb-1">Notes:</h5>
          <p class="mb-0">All accounts are to be paid within 7 days from receipt of invoice. To be paid by cheque or credit card or direct payment online. If account is not paid within 7 days the credits details supplied as confirmation of work undertaken will be charged the agreed quoted fee noted above.</p>
      </div>
      <div class="mt-6">
        <a href="#" class="btn btn-primary print-link no-print">Print</a>
        <a href="#" class="btn btn-danger ms-2">Download</a>
    </div>
  </div>
</div>
</div>
{% endblock content %}

templates/Exporter/Dashboard/stocks.html
{% extends 'Exporter/Dashboard/base.html' %}
{% block content %}



<div id="app-content">
    <div class="app-content-area">
      <!-- Container fluid -->
      <div class="container-fluid">
        <div class="row">
          <div class=" col-xl-9 col-md-12 col-sm-12 col-12 ">
            <!-- Content -->
                
            
            <div class="page-header">
                    <h1>Warehouse Details</h1>
            </div>

          <table class="table table-bordered">
            <thead>
              <tr class="table-primary">
                <th scope="col">WareHouse</th>
                <th scope="col">Types</th>
                <th scope="col">Stock In Units</th>
                <th scope="col">Prices in Rs.</th>
              </tr>
            </thead>
            <tbody>
              {% for warehouse in warehouses %}
              {% for wh_type in warehouse.warehousetype_set.all %}
              <tr>
                {% if forloop.first %}
                <td rowspan="{{ warehouse.warehousetype_set.count }}">{{ warehouse.w_name }}</td>
                {% endif %}
                <td>{{ wh_type.type.type_name }}</td>
                <td>{{ wh_type.stock_capacity }}</td>
                <td>{{ wh_type.price_per_unit }}</td>
              </tr>
              {% endfor %}
              {% endfor %}
            </tbody>
          </table>


                </div>
               
              </div>



            </div>
        </div>
    </div>
</div>


{% endblock content %}